articles = [
    "https://mitchellh.com/writing/everyone-should-know-simd",
    "https://blog.codeberg.org/protecting-our-floss-commons-from-llms.html",
    "https://world.hey.com/dhh/sitting-down-with-senra-69f5e368",
    "https://world.hey.com/dhh/three-sacred-cows-that-must-die-so-europe-can-live-1afb203d",
    "https://world.hey.com/dhh/endless-execution-4157e065",
    "https://world.hey.com/dhh/dell-is-on-a-roll-with-the-xps-5a09a84e",
    "https://andrewkelley.me/post/dont-take-black-pill.html",
    "https://world.hey.com/dhh/i-m-sorry-dave-380ec27d",
    "https://mitchellh.com/writing/superlogical",
    "https://world.hey.com/dhh/wolves-sheep-and-gypsies-ba44af6a",
]
