articles = [
    "https://blog.codeberg.org/protecting-our-floss-commons-from-llms.html",
    "https://world.hey.com/dhh/endless-execution-4157e065",
    "https://www.dr.dk/nyheder/udland/ny-anbefaling-skal-saette-graense-antal-boern-per-saeddonor",
    "https://www.dr.dk/nyheder/udland/reels/kvinde-reddes-ud-af-delvist-kollapset-bygning-i-colombia",
    "https://world.hey.com/dhh/sitting-down-with-senra-69f5e368",
    "https://www.dr.dk/nyheder/indland/reels/laerere-er-en-mangelvare-nu-tyer-flere-kommuner-til-et-nyt-kneb",
    "https://www.dr.dk/nyheder/udland/reels/doedstal-ventes-stige-efter-jordskaelv-i-colombia",
    "https://www.dr.dk/nyheder/udland/man-skulle-virkelig-kaempe-staa-op-20-aarige-ida-madsine-frygtede-sit-liv-under-jordskaelv",
    "https://www.dr.dk/nyheder/udland/sveriges-statsminister-laegger-ikke-fingrene-i-mellem-spaniens-udstrakte-haand-til-papirloese",
    "https://www.dr.dk/nyheder/udland/colombia-erklaerer-noedsituation-efter-voldsomt-jordskaelv",
    "https://mitchellh.com/writing/superlogical",
    "https://www.dr.dk/nyheder/indland/reels/efter-30-aar-i-tingbjerg-har-anja-faaet-nok",
    "https://world.hey.com/dhh/dell-is-on-a-roll-with-the-xps-5a09a84e",
    "https://www.dr.dk/nyheder/udland/sidste-aar-oploeste-pkk-sig-selv-nu-giver-tyrkiet-delvis-amnesti-til-militante",
    "https://www.dr.dk/nyheder/indland/i-dag-starter-elever-i-11-og-12-klasse-et-nyt-tilbud-til-elever-i-mistrivsel",
    "https://mitchellh.com/writing/everyone-should-know-simd",
    "https://www.dr.dk/nyheder/udland/rhinen-er-af-central-betydning-den-tyske-oekonomi-men-lige-nu-toerster-den-efter-vand",
    "https://www.dr.dk/nyheder/indland/22-aarig-ungarsk-mand-varetaegtsfaengslet-i-sag-om-15-aarig-dansk-pige",
    "https://www.dr.dk/nyheder/udland/spaniens-udenrigsminister-enhver-der-forsoeger-rejse-ind-i-ceuta-vil-blive-sendt-tilbage",
    "https://world.hey.com/dhh/wolves-sheep-and-gypsies-ba44af6a",
    "https://www.dr.dk/nyheder/udland/mette-frederiksen-og-giorgia-meloni-staar-sammen-paa-sociale-medier-det-her-er-politisk-saerdeles",
    "https://www.dr.dk/nyheder/udland/ny-magtbalance-i-mellemoesten-usa-faar-en-mindre-rolle",
    "https://www.dr.dk/nyheder/indland/tidligere-kongelig-konfessionarius-og-biskop-erik-norman-svendsen-er-doed",
    "https://www.dr.dk/nyheder/indland/et-udtryk-desperation-kommuner-nu-selv-proever-loese-laerermangel",
    "https://www.dr.dk/nyheder/udland/reels/russiske-angreb-draeber-seks-personer",
    "https://www.dr.dk/nyheder/indland/jagten-paa-problemulv-i-vestjylland-intensiveres-minister-er-foerst-tilfreds-naar-den-her-ulv-er",
    "https://www.dr.dk/nyheder/indland/spoerger-du-altid-dine-boern-om-hvad-de-har-laert-i-skolen-maaske-skal-du-stille-et-helt-andet",
    "https://world.hey.com/dhh/i-m-sorry-dave-380ec27d",
    "https://www.dr.dk/nyheder/indland/flere-unge-med-lave-karakterer-vaelger-gymnasiet",
    "https://www.dr.dk/nyheder/indland/nyt-fiskerieventyr-paa-vej-laesoe-fiskere-vil-fange-tun",
    "https://www.dr.dk/nyheder/indland/live-problemulv-jages-med-droner",
    "https://www.dr.dk/nyheder/indland/koebenhavns-kommune-opsiger-samarbejdet-med-dao",
    "https://www.dr.dk/nyheder/udland/analyse-spionsagen-fra-stockholm-kommer-ikke-som-nogen-overraskelse",
    "https://www.dr.dk/nyheder/udland/reels/forsker-vi-overvurderer-demokraternes-venstredrejning",
    "https://www.dr.dk/nyheder/udland/kold-luft-og-et-kontant-nej-kan-trump-redde-sin-fredsplan",
    "https://www.dr.dk/nyheder/indland/dommer-loeslader-mand-ramt-af-politiets-skud",
    "https://www.dr.dk/nyheder/indland/mens-droner-leder-efter-en-problemulv-luntede-der-i-aftes-en-ulv-rundt-ved-en-familierestaurant",
    "https://world.hey.com/dhh/three-sacred-cows-that-must-die-so-europe-can-live-1afb203d",
    "https://www.dr.dk/nyheder/indland/yoga-teknologivaerksted-og-voksne-skal-give-bedre-frikvarter",
    "https://www.dr.dk/nyheder/udland/mindst-111-mennesker-har-mistet-livet-i-jordskaelv-i-colombia-alt-faldt-sammen-alt-revnede-siger",
    "https://www.dr.dk/nyheder/indland/kommune-vil-undersoege-arbejdsforholdene-op-til-skoleleders-selvmord",
    "https://www.dr.dk/nyheder/udland/jordskaelv-bliver-foerste-store-proeve-colombias-nye-praesident",
    "https://www.dr.dk/nyheder/udland/mange-ser-hende-som-demokraternes-unge-haab-men-praesidentposten-kan-vaere-uden-raekkevidde",
    "https://www.dr.dk/nyheder/indland/emil-thorup-har-droppet-noget-af-den-sundhedsrutine-han-er-blevet-saa-kendt",
    "https://www.dr.dk/nyheder/udland/syriens-tidligere-praesident-assad-idoemt-doedsstraf-absentia",
    "https://www.dr.dk/nyheder/indland/usaedvanligt-festivaljob-bliv-hemmelig-gaest-og-vind-20-000-kroner",
    "https://www.dr.dk/nyheder/indland/oejenvidner-og-ekspert-kritiserer-sikkerheden-paa-smukfest",
]
